---
version: "3.3" 

networks:
  net:

services: 

  db:
    image: 'mysql:latest'
    container_name: mysql_db
    volumes:
      - './db_data:/var/lib/mysql'
    environment: 
      - MYSQL_DATABASE=projectDB
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'
    ports:
      - '3306:3306'
    networks:
      - net 
    expose:
      - '3306'

  web:
    depends_on:
      - db
    image: django-ui
    container_name: Django-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    command: >      
     bash -c "./wait-for-it.sh db:3306 -- python manage.py migrate
     && python manage.py runserver 0.0.0.0:8000"


    volumes:
      - './django_data:/var/lib/django_data' 
    networks:
      - net
    
    
    
    



    
      