apiVersion: v1
kind: Service
metadata: 
  name: mysql-app-service
spec:
  type: NodePort
  selector:
    app: mysql-app
  ports:
    - portocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31000