apiVersion: v1
kind: Service
metadata: 
  name: django-app-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - portocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31100