# Generated by Django 3.1.1 on 2020-09-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Upload1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Air_Pollution',
            },
        ),
        migrations.CreateModel(
            name='Upload2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Electricity',
            },
        ),
        migrations.CreateModel(
            name='Upload3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Road_Construction',
            },
        ),
        migrations.CreateModel(
            name='Upload4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Sewage_&_Water_Logging',
            },
        ),
        migrations.CreateModel(
            name='Upload5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Waste_Management',
            },
        ),
        migrations.CreateModel(
            name='Upload6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'U_Others',
            },
        ),
    ]
